// Code generated by zod2go. DO NOT EDIT.

package insomnia

// InsomniaFile Insomnia v5 export format schemas
type InsomniaFile any // Union type - see oneOf/anyOf variants

type ApiSpec struct {
	Certificates []any `json:"certificates,omitempty"`
	Collection []any `json:"collection,omitempty"`
	CookieJar *any `json:"cookieJar,omitempty"`
	Environments *any `json:"environments,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
	SchemaVersion *string `json:"schema_version,omitempty"`
	Spec *any `json:"spec,omitempty"`
	TestSuites []any `json:"testSuites,omitempty"`
	Type string `json:"type"`
}

type Collection struct {
	Certificates []any `json:"certificates,omitempty"`
	Collection []any `json:"collection,omitempty"`
	CookieJar *any `json:"cookieJar,omitempty"`
	Environments *any `json:"environments,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
	SchemaVersion *string `json:"schema_version,omitempty"`
	Type string `json:"type"`
}

type CookieJar struct {
	Cookies []any `json:"cookies,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
}

type Environment struct {
	Color *any `json:"color,omitempty"`
	Data *any `json:"data,omitempty"`
	DataPropertyOrder *any `json:"dataPropertyOrder,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
	SubEnvironments []any `json:"subEnvironments,omitempty"`
}

type GRPCRequest struct {
	Body *any `json:"body,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Metadata []any `json:"metadata,omitempty"`
	Name *string `json:"name,omitempty"`
	ProtoFileId *any `json:"protoFileId,omitempty"`
	ProtoMethodName *string `json:"protoMethodName,omitempty"`
	ReflectionApi any `json:"reflectionApi"`
	Url *string `json:"url,omitempty"`
}

type Headers []any

type McpClient struct {
	Environments *any `json:"environments,omitempty"`
	McpRequest *any `json:"mcpRequest,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
	SchemaVersion *string `json:"schema_version,omitempty"`
	Type string `json:"type"`
}

type McpRequest struct {
	Authentication *any `json:"authentication,omitempty"`
	Env []any `json:"env,omitempty"`
	Headers []any `json:"headers,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
	Roots []any `json:"roots,omitempty"`
	TransportType *string `json:"transportType,omitempty"`
	Url *string `json:"url,omitempty"`
}

type Meta struct {
	Created *float64 `json:"created,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	IsPrivate *bool `json:"isPrivate,omitempty"`
	Modified *float64 `json:"modified,omitempty"`
	SortKey *float64 `json:"sortKey,omitempty"`
}

type MockRoute struct {
	Body *string `json:"body,omitempty"`
	Headers []any `json:"headers,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Method *string `json:"method,omitempty"`
	MimeType *string `json:"mimeType,omitempty"`
	Name *string `json:"name,omitempty"`
	StatusCode *float64 `json:"statusCode,omitempty"`
	StatusText *string `json:"statusText,omitempty"`
}

type MockServer struct {
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
	Routes []any `json:"routes,omitempty"`
	SchemaVersion *string `json:"schema_version,omitempty"`
	Server *any `json:"server,omitempty"`
	Type string `json:"type"`
}

type Request struct {
	Authentication *any `json:"authentication,omitempty"`
	Body *any `json:"body,omitempty"`
	Headers []any `json:"headers,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Method string `json:"method"`
	Name *string `json:"name,omitempty"`
	Parameters []any `json:"parameters,omitempty"`
	PathParameters *any `json:"pathParameters,omitempty"`
	Scripts *any `json:"scripts,omitempty"`
	Settings *any `json:"settings,omitempty"`
	Url *string `json:"url,omitempty"`
}

type RequestGroup struct {
	Authentication *any `json:"authentication,omitempty"`
	Children []any `json:"children,omitempty"`
	Environment *any `json:"environment,omitempty"`
	EnvironmentPropertyOrder *any `json:"environmentPropertyOrder,omitempty"`
	Headers []any `json:"headers,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
	Scripts *any `json:"scripts,omitempty"`
}

type RequestSettings struct {
	Cookies any `json:"cookies"`
	EncodeUrl *bool `json:"encodeUrl,omitempty"`
	FollowRedirects *string `json:"followRedirects,omitempty"`
	RebuildPath *bool `json:"rebuildPath,omitempty"`
	RenderRequestBody *bool `json:"renderRequestBody,omitempty"`
}

type Scripts struct {
	AfterResponse *string `json:"afterResponse,omitempty"`
	PreRequest *string `json:"preRequest,omitempty"`
}

type SocketIOEventListener struct {
	Desc *string `json:"desc,omitempty"`
	EventName *string `json:"eventName,omitempty"`
	Id string `json:"id"`
	IsOpen *bool `json:"isOpen,omitempty"`
}

type SocketIORequest struct {
	Authentication *any `json:"authentication,omitempty"`
	EventListeners []any `json:"eventListeners,omitempty"`
	Headers []any `json:"headers,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
	Parameters []any `json:"parameters,omitempty"`
	PathParameters []any `json:"pathParameters,omitempty"`
	Settings *any `json:"settings,omitempty"`
	Url *string `json:"url,omitempty"`
}

type WebsocketRequest struct {
	Authentication *any `json:"authentication,omitempty"`
	Headers []any `json:"headers,omitempty"`
	Meta *any `json:"meta,omitempty"`
	Name *string `json:"name,omitempty"`
	Parameters []any `json:"parameters,omitempty"`
	PathParameters *any `json:"pathParameters,omitempty"`
	Settings *any `json:"settings,omitempty"`
	Url *string `json:"url,omitempty"`
}

